### ISSUE TITLE
termios.error

### ISSUE THREAD

**Issue by catdogsbob** [cmccandless/easy_getch#2]
Running on pi zero, install no error. Python 3.7 i was working on a project get the same problem even if i run this:
"
from easy_getch import getch

ch = getch()
print(ch)

i get 
traceback (most recent call last)
 ch = getch()
"
return self.impl()

old_settings = termios.tcgetattr(fd0
termios.error: (25, 'inappropriate ioctl for device')

**Comment by cmccandless** [comment]
I'm afraid this package hasn't been under active development for 2 years, and I don't currently have access to a similar setup to reproduce. Feel free to investigate the package source code to attempt a fix. If you discover one, please submit a pull request.
